### ISSUE TITLE
Variables in mixin arguments

### ISSUE THREAD

**Issue by mrmartineau** [MaciekBaron/sublime-list-stylesheet-vars#4]
Scss, Sass and Less (I'm not sure about Stylus) allow variables as arguments in mixins. I believe these vars should not be displayed in the output; have a look at the grab below to see the unintentional output when calling the plugin from within a mixins file. All mixins have a fairly generic syntax so I think we can safely ignore these by tweaking the regex slightly.

![](http://cl.ly/PMdb/Screen%20Shot%202013-06-02%20at%2019.12.58.png)
### Scss mixin syntax:

``` scss
@mixin box-shadow($shadow: 0 1px 3px rgba(0,0,0,.25)) {
-webkit-box-shadow: $shadow;
   -moz-box-shadow: $shadow;
     -o-box-shadow: $shadow;
        box-shadow: $shadow;
}
```
### Sass mixin syntax:

``` sass
@mixin box-shadow($shadow: 0 1px 3px rgba(0,0,0,.25)) 
-webkit-box-shadow: $shadow
   -moz-box-shadow: $shadow
     -o-box-shadow: $shadow
        box-shadow: $shadow
```
### Less mixin syntax:

``` scss
.box-shadow(@shadow: 0 1px 3px rgba(0,0,0,.25)) {
  -webkit-box-shadow: @shadow;
     -moz-box-shadow: @shadow;
          box-shadow: @shadow;
}
```
### Stylus mixin syntax:

``` css
border-radius()
  -webkit-border-radius arguments
  -moz-border-radius arguments
  border-radius arguments
```
